import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Áo POLO  nam POTTK331",
      slug: "ao-polo-nam-pottk331",
      category: "Polos",
      image: "/images/polo/polo_1.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK332",
      slug: "ao-polo-nam-pottk332",
      category: "Polos",
      image: "/images/polo/polo_2.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK333",
      slug: "ao-polo-nam-pottk333",
      category: "Polos",
      image: "/images/polo/polo_3.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK334",
      slug: "ao-polo-nam-pottk334",
      category: "Polos",
      image: "/images/polo/polo_4.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK335",
      slug: "ao-polo-nam-pottk335",
      category: "Polos",
      image: "/images/polo/polo_5.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK336",
      slug: "ao-polo-nam-pottk336",
      category: "Polos",
      image: "/images/polo/polo_6.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK337",
      slug: "ao-polo-nam-pottk337",
      category: "Polos",
      image: "/images/polo/polo_7.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Áo POLO  nam POTTK338",
      slug: "ao-polo-nam-pottk338",
      category: "Polos",
      image: "/images/polo/polo_8.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "SM BAMBOO",
      slug: "sm-bamboo",
      category: "Shirts",
      image: "/images/shirt/shirt_1.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "POLO CS",
      slug: "polo-cs",
      category: "Shirts",
      image: "/images/shirt/shirt_2.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },

    {
      name: "BIKER Da lộn",
      slug: "biker-da-lon",
      category: "Bikers",
      image: "/images/biker/biker_1.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "BOMBER Da lộn",
      slug: "bomber-da-lon",
      category: "Bombers",
      image: "/images/bomber/bomber_1.jpg",
      price: 525,
      brand: "CEFFYLO",
      rating: "4.2",
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
  ],
};
export default data;
